lib: [
  "_build/default/src/llama_tetris.cmxs"
  "_build/default/src/llama_tetris.a"
  "_build/default/src/llama_tetris.cmxa"
  "_build/default/src/llama_tetris.cma"
  "_build/default/src/view.mli"
  "_build/default/src/llama_tetris__View.cmti"
  "_build/default/src/llama_tetris__View.cmt"
  "_build/default/src/llama_tetris__View.cmx"
  "_build/default/src/llama_tetris__View.cmi"
  "_build/default/src/llama_tetris.ml-gen"
  "_build/default/src/llama_tetris.cmt"
  "_build/default/src/llama_tetris.cmx"
  "_build/default/src/llama_tetris.cmi"
  "_build/default/src/geom.mli"
  "_build/default/src/llama_tetris__Geom.cmti"
  "_build/default/src/llama_tetris__Geom.cmt"
  "_build/default/src/llama_tetris__Geom.cmx"
  "_build/default/src/llama_tetris__Geom.cmi"
  "_build/default/src/game_state.mli"
  "_build/default/src/llama_tetris__Game_state.cmti"
  "_build/default/src/llama_tetris__Game_state.cmt"
  "_build/default/src/llama_tetris__Game_state.cmx"
  "_build/default/src/llama_tetris__Game_state.cmi"
  "_build/default/src/board.mli"
  "_build/default/src/llama_tetris__Board.cmti"
  "_build/default/src/llama_tetris__Board.cmt"
  "_build/default/src/llama_tetris__Board.cmx"
  "_build/default/src/llama_tetris__Board.cmi"
  "_build/default/src/actor.mli"
  "_build/default/src/llama_tetris__Actor.cmti"
  "_build/default/src/llama_tetris__Actor.cmt"
  "_build/default/src/llama_tetris__Actor.cmx"
  "_build/default/src/llama_tetris__Actor.cmi"
  "_build/default/META.llama-tetris" {"META"}
]
bin: [
  "_build/default/bin/main.exe" {"tetris"}
]
doc: [
  "README"
  "LICENSE"
]
